export const cartTypes = {
    TOGGLE_CART_COMPONENT :"TOGGLE_CART_COMPONENT",
    ADD_ITEM:"ADD_ITEM",
    CLEAR_ITEM:"CLEAR_ITEM",
    REMOVE_ITEM:"REMOVE_ITEM",
    CLEAR_ITEM_FROM_CART:"CLEAR_ITEM_FROM_CART"
}